# 네이버 뉴스 카테고리 분류기 만들기

## 자연어처리 라이브러리 설치

In [ ]:
# nltk.download()  # 텍스트 데이터 처리를 위한 패키지 다운로더

# Download following packages
# Corpora : stopwords, wordnet
# Models : averaged_perceptron_tagger, maxent_treebank_pos_tagger, punkt
import nltk
nltk.download()

In [ ]:
# Install konlpy
!curl -s https://raw.githubusercontent.com/teddylee777/machine-learning/master/99-Misc/01-Colab/mecab-colab.sh | bash

## 데이터셋 불러오기

In [ ]:
from google.colab import drive
drive.mount('/content/drive') # 원하는 세부 경로로 변경이 불가능합니다.

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

csv_list = ['/content/drive/MyDrive/data/result_231210_0111.csv',
            '/content/drive/MyDrive/data/result_231210_0206.csv',
            '/content/drive/MyDrive/data/result_231210_0239.csv',
            '/content/drive/MyDrive/data/result_231210_0127.csv',
            '/content/drive/MyDrive/data/result_231210_0221.csv']
news_df = pd.DataFrame()
for csv in csv_list:
    df_data = pd.read_csv(csv)
    news_df = news_df.append(df_data)

print('전체 리뷰 수:', len(news_df))
news_df.head()

<ipython-input-68-01b5cf4e2e87>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_df = news_df.append(df_data)
<ipython-input-68-01b5cf4e2e87>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_df = news_df.append(df_data)
<ipython-input-68-01b5cf4e2e87>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_df = news_df.append(df_data)
<ipython-input-68-01b5cf4e2e87>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_df = news_df.append(df_data)


전체 리뷰 수: 2316


<ipython-input-68-01b5cf4e2e87>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_df = news_df.append(df_data)


date category   press                                title  \
0  2023.11.29. 오후 12:00       사회    연합뉴스  3분기 출산율 0.7명 '역대 최저'…0.6명대 추락 '빨간불'   
1   2023.11.29. 오후 6:04       경제    한국경제   통계나올 때마다 '쇼크'…3분기 출산율 0.7명 또 역대 최저   
2   2023.11.30. 오전 5:03       사회    서울신문            3분기도 출산율 최저… 올 0.7명도 위태롭다   
3   2023.11.29. 오후 3:29       경제  한경비즈니스      “이러다 한국 진짜 망한다”...또 다시 ‘출산율 쇼크’   
4   2023.11.29. 오후 9:33       경제    TV조선   3분기 합계 출산율, 0.7명…올해 출생아 20만 명대 턱걸이   

                                            document  \
0  통계청, 9월 인구동향…작년 3분기比 0.1명↓47개월째 인구 자연감소(세종=연합뉴...   
1  통계청 인구동향17개 광역시·도 일제히 하락광주 0.2명 줄어 하락폭 최대 인구 4...   
2  1년 전보다 0.1명 줄어들어 0.7명9월 출생아 수·혼인도 가장 낮아다문화 혼인은...   
3  3분기 합계출산율 0.7명 기록3분기 기준 역대 최저치4분기에는 더 떨어질 가능성 ...   
4  [앵커]출산율 감소, 혼인율 감소 저도 계속   전하는 입장에서 뾰족한  대책이 없...   

                                                link  
0  https://n.news.naver.com/mnews/article/001/001...  
1  https://n.news.naver.com/mnews/article/015/000...  
2  https://n.news.naver.com/mnews/article/081/000...  
3  https://n.news.naver.com/mnews/article/050/000...  
4  https://n.news.naver.com/mnews/article/448/000...

In [71]:
news_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2316 entries, 0 to 469
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   date      2316 non-null   object
 1   category  2316 non-null   object
 2   press     2316 non-null   object
 3   title     2316 non-null   object
 4   document  2307 non-null   object
 5   link      2316 non-null   object
dtypes: object(6)
memory usage: 126.7+ KB


In [72]:
news_df = news_df.dropna()

In [73]:
set(news_df['category'])

{'IT', '경제', '사회', '생활', '세계', '오피니언', '정치'}

In [74]:
news_df['category'].value_counts()

사회      744
경제      713
생활      336
IT      186
세계      182
오피니언     78
정치       68
Name: category, dtype: int64

In [ ]:
import re

def tokenize_and_stemming(sentence, tokenizer):

    sentence = re.sub("[^\s0-9a-zA-Zㄱ-ㅎㅏ-ㅣ가-힣]", "", sentence)

    raw_pos_tagged = tokenizer.pos(sentence, stem=True) # POS Tagging with stemming

    sentence_tokenized = []
    for token, pos in raw_pos_tagged: # ex) word <- ('서울', 'Noun')
        # pos 기준 제거 대상 : ["Josa", "Eomi", "Punctuation", "Foreign", "Number", "Suffix", "Determiner"]
        # 리뷰 텍스트 상 형태소의 순서를 고려하는 경우 의미를 갖게 됨 : "VerbPrefix" (잘/안/못), "Conjunction"(하지만/그러나/그리고), "KoreanParticle"(ㅋㅋㅋ/ㅎㅎㅎ/ㅠㅠ)
        if (len(token) != 1) & (pos in ["Noun", "VerbPrefix", "Verb", "Adverb", "Adjective", "Conjunction", "KoreanParticle"]):
            sentence_tokenized.append(token)

    return sentence_tokenized

In [75]:
from konlpy.tag import Okt
import tqdm

okt = Okt()
tokenized_sentences = []

for sentence in tqdm.tqdm(news_df['document']):
    try:
        tokenized_sentences.append(tokenize_and_stemming(sentence, okt))
    except:
        print("Error occured at :", sentence)
        tokenized_sentences.append([])

news_df['document'] = tokenized_sentences

100%|██████████| 2307/2307 [04:18<00:00,  8.94it/s]


In [76]:
# https://scikit-learn.org/stable/auto_examples/compose/plot_column_transformer_mixed_types.html

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [77]:
categories = news_df['category'].tolist()
le.fit(categories)
news_df['category'] = le.transform(categories)
news_df['category'].value_counts()

2    744
1    713
3    336
0    186
4    182
5     78
6     68
Name: category, dtype: int64

In [78]:
news_df.head()

date  category   press  \
0  2023.11.29. 오후 12:00         2    연합뉴스   
1   2023.11.29. 오후 6:04         1    한국경제   
2   2023.11.30. 오전 5:03         2    서울신문   
3   2023.11.29. 오후 3:29         1  한경비즈니스   
4   2023.11.29. 오후 9:33         1    TV조선   

                                 title  \
0  3분기 출산율 0.7명 '역대 최저'…0.6명대 추락 '빨간불'   
1   통계나올 때마다 '쇼크'…3분기 출산율 0.7명 또 역대 최저   
2            3분기도 출산율 최저… 올 0.7명도 위태롭다   
3      “이러다 한국 진짜 망한다”...또 다시 ‘출산율 쇼크’   
4   3분기 합계 출산율, 0.7명…올해 출생아 20만 명대 턱걸이   

                                            document  \
0  [통계청, 인구, 동향, 작년, 개월, 인구, 자연, 감소, 세종, 연합뉴스, 이준...   
1  [통계청, 인구, 동향, 광역시, 일제, 하락, 광주, 줄다, 하락, 최대, 인구,...   
2  [전보, 줄어들다, 출생, 혼인, 가장, 낮다, 다문화, 혼인, 늘다, 올해, 합계...   
3  [합계출산율, 기록, 기준, 역대, 최저, 떨어지다, 가능성, 높다, 통계청, 발표...   
4  [앵커, 출산율, 감소, 혼인, 감소, 계속, 전하, 입장, 뾰족, 대책, 없다, ...   

                                                link  
0  https://n.news.naver.com/mnews/article/001/001...  
1  https://n.news.naver.com/mnews/article/015/000...  
2  https://n.news.naver.com/mnews/article/081/000...  
3  https://n.news.naver.com/mnews/article/050/000...  
4  https://n.news.naver.com/mnews/article/448/000...

## 트레이닝/테스트 셋으로 나누기

In [79]:
from sklearn import model_selection

train_x, test_x, train_y, test_y = model_selection.train_test_split(news_df['document'], news_df['category'],
                                                                    test_size=0.4,
                                                                    random_state=42,
                                                                    stratify=news_df['category']
                                                                    )

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer # CountVectorizer

def list_to_list(doc):
    return doc

vectorizer = TfidfVectorizer(tokenizer=list_to_list, token_pattern=None, lowercase=False) # CountVectorizer 적용 시 아주 약간 성능 저하 (88.15% -> 88.02%)
vectorizer.fit(train_x)

train_x_vector = vectorizer.transform(train_x) # .toarray() 함수를 연달아 적용하면 np.array 형태로 만들어진 행렬을 확인할 수 있으나, RAM이 초과되어 Colab이 초기화됩니다.
test_x_vector = vectorizer.transform(test_x)

## 모델 생성

In [82]:
from sklearn.naive_bayes import MultinomialNB, ComplementNB
mnb_clf = MultinomialNB(force_alpha=True)
cnb_clf = ComplementNB(force_alpha=True)

## 모델 학습

In [83]:
import numpy as np

x = train_x_vector.toarray()

mnb_clf.fit(train_x_vector, train_y)

MultinomialNB(force_alpha=True)

In [84]:
cnb_clf.fit(train_x_vector, train_y)

ComplementNB(force_alpha=True)

## 테스트 데이터 예측

In [85]:
mnb_pred_y = mnb_clf.predict(test_x_vector)
cnb_pred_y = cnb_clf.predict(test_x_vector)

# 모델 평가

## Cross Validation

In [86]:
from sklearn.model_selection import cross_val_score
mnb_mean = sum(cross_val_score(mnb_clf, train_x_vector, train_y, cv=5))/5
print(mnb_mean)

0.677706273217182


In [87]:
cnb_mean = sum(cross_val_score(cnb_clf, train_x_vector, train_y, cv=5))/5
print(cnb_mean)

0.7145450740333803


## Accuracy score

In [88]:
cnb_clf.score(test_x_vector, test_y)

from sklearn.metrics import accuracy_score

accuracy_score(test_y, cnb_pred_y)

0.7031419284940412

## Classification Report

In [89]:
from sklearn.metrics import classification_report
print(classification_report(test_y, cnb_pred_y))

              precision    recall  f1-score   support

           0       0.54      0.43      0.48        74
           1       0.74      0.76      0.75       285
           2       0.80      0.74      0.77       298
           3       0.71      0.88      0.79       135
           4       0.45      0.74      0.56        73
           5       1.00      0.03      0.06        31
           6       1.00      0.19      0.31        27

    accuracy                           0.70       923
   macro avg       0.75      0.54      0.53       923
weighted avg       0.73      0.70      0.69       923



## Confusion matrix

In [90]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_y, cnb_pred_y))

[[ 32   5   6   0  31   0   0]
 [ 16 217  19   5  28   0   0]
 [  2  29 221  44   2   0   0]
 [  2   6   8 119   0   0   0]
 [  4  14   1   0  54   0   0]
 [  3  17   6   0   4   1   0]
 [  0   6  16   0   0   0   5]]


## 모델 저장

In [91]:
import joblib

joblib.dump(cnb_clf, 'clf_news_CNB_v2.pkl', compress=True)

['clf_news_CNB_v2.pkl']