<br>
<br>

### (Official) Installation guide @ https://pytorch.org/get-started/locally/

In [20]:
!pip install torch --upgrade
!pip install torchvision --upgrade
!pip install torchaudio --upgrade

# "액세스가 거부되었습니다" 에러가 발생하거나 정상적으로 설치가 진행되지 않을 경우,
# cmd(명령프롬프트) 우클릭 & 관리자권한으로 실행 후,
# 느낌표를 제외한 명령어를 1줄씩 입력 & 실행하여 설치를 진행합니다.

  Using cached sympy-1.12.1-py3-none-any.whl.metadata (12 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 MB 11.2 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 9.0 MB/s eta 0:00:00
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 11.0 MB/s eta 0:00:00a 0:00:01
Using cached sympy-1.12.1-py3-none-any.whl (5.7 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
  Attempting uninstall: torch
    Found existing installation: torch 1.10.2
    Uninstalling torch-1.10.2:
      Successfully uninstalled torch-1.10.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 10.8 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.11.3
    Uninstalling torchvision-0.11.3:
      Successfully uninstalled torchvis

In [1]:
import torch, torchvision, torchaudio

print(torch.__version__)
print(torchvision.__version__)
print(torchaudio.__version__)

2.3.1
0.18.1
2.3.1


In [3]:
print(f"MPS 장치를 지원하도록 build 되었는지: {torch.backends.mps.is_built()}") # True 여야 합니다.
print(f"MPS 장치가 사용 가능한지: {torch.backends.mps.is_available()}") # True 여야 합니다.


MPS 장치를 지원하도록 build 되었는지: True
MPS 장치가 사용 가능한지: True


In [44]:
device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
print(f"device: {device}")

device: mps


In [4]:
!python -c 'import platform;print(platform.platform())'

macOS-14.5-arm64-arm-64bit


<br>
<br>

# 1. Tensors
<br>

- (Official) **torch.Tensor** @ https://pytorch.org/docs/stable/tensors.html

In [ ]:
import torch

<br>
<br>

### 1) **Scalar** == a single number == a zero dimension tensor

<br>

#### \+ ndim / shape / dtype / device
#### \+ item() / type()

In [5]:
scalar = torch.tensor(3) # tensor 자료형 변수 만들기

scalar

tensor(3)

In [6]:
scalar.ndim # 차원 갯수 체크 (Number of Dimension)

0

In [7]:
scalar.shape # 각 차원별 데이터 수 체크 (== np.ndarray.shape)

torch.Size([])

In [8]:
scalar.dtype # 데이터 타입 체크 

torch.int64

In [63]:
scalar.device # tensor 변수가 현재 할당된 장치(device) 체크

device(type='cpu')

In [8]:
scalar.item() # tensor 변수 내부의 값(item) 꺼내기 <- only works with one-element tensors

3

In [9]:
# Type-casting

scalar.type(torch.float16).item() # 자료형 변환 (type 함수 활용)

3.0

<br>
<br>

### 2) **vector** == an array == a single dimension tensor

In [13]:
vector = torch.tensor([1, 2, 3])

vector

tensor([1, 2, 3])

In [14]:
vector.ndim # 1차원 벡터

1

In [15]:
vector.shape # == np.ndarray.shape

torch.Size([3])

In [17]:
vector.item()

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [18]:
vector[2].item() # index 번호로 scalar tensor 꺼낸 후 값(item) 꺼내기

3

<br>
<br>

### 3) **matrix** == a multiple dimension tensor

In [19]:
matrix = torch.tensor([[1, 2, 3], 
                       [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
matrix.ndim # 2차원 행렬

2

In [21]:
matrix.shape # == np.ndarray.shape

torch.Size([2, 3])

In [22]:
matrix[1, 2].item() # indexing 

6

<br>
<br>

### 4) random / zeros / ones / arange

In [23]:
random_tensor = torch.rand(size=(2, 3)) # 랜덤 값들로 채워진 텐서 생성

random_tensor

tensor([[0.8115, 0.0051, 0.2005],
        [0.6543, 0.9867, 0.3853]])

In [24]:
random_tensor.dtype

torch.float32

In [25]:
random_tensor = torch.rand(size=(2, 3), dtype=torch.float16)

random_tensor

tensor([[0.4077, 0.7573, 0.2139],
        [0.8613, 0.7832, 0.3706]], dtype=torch.float16)

In [26]:
random_tensor.dtype

torch.float16

In [27]:
random_tensor.shape # 각 차원별 데이터 수 체크 (== np.ndarray.shape)

torch.Size([2, 3])

In [28]:
zeros = torch.zeros(size=(2, 3))

zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [29]:
ones = torch.ones(size=(2, 3))

ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [30]:
arange = torch.arange(3, 15, 2) # array of range

arange

tensor([ 3,  5,  7,  9, 11, 13])

In [31]:
zeros_like = torch.zeros_like(arange)

zeros_like

tensor([0, 0, 0, 0, 0, 0])

<br>
<br>

# 2. Tensor operations


<br>
<br>

### Descriptive stats / argmax / matrix calculation / reshape

In [32]:
random_tensor = torch.rand(size=(2, 3), dtype=torch.float16)

random_tensor

tensor([[0.7183, 0.5918, 0.7715],
        [0.0015, 0.4590, 0.6074]], dtype=torch.float16)

In [33]:
print(random_tensor.min().item()) # 최소
print(random_tensor.max().item()) # 최대
print(random_tensor.mean().item()) # 평균
print(random_tensor.std().item()) # 표준편차
print(random_tensor.sum().item()) # 합계

0.00146484375
0.771484375
0.52490234375
0.278564453125
3.1484375


In [34]:
print(torch.min(random_tensor).item()) # 최소
print(torch.max(random_tensor).item()) # 최대
print(torch.mean(random_tensor).item()) # 평균
print(torch.std(random_tensor).item()) # 표준편차
print(torch.sum(random_tensor).item()) # 합계

0.00146484375
0.771484375
0.52490234375
0.278564453125
3.1484375


In [35]:
random_tensor

tensor([[0.7183, 0.5918, 0.7715],
        [0.0015, 0.4590, 0.6074]], dtype=torch.float16)

In [36]:
random_tensor.argmax(dim=0) # 열 방향으로 가장 큰 값들의 index 번호 확인하기

tensor([0, 0, 0])

In [37]:
random_tensor.argmax(dim=1) # 행 방향으로 가장 큰 값들의 index 번호 확인하기

tensor([2, 2])

In [38]:
tensor = torch.tensor([1, 2, 3])

tensor

tensor([1, 2, 3])

In [39]:
tensor + 10 # numpy-like

tensor([11, 12, 13])

In [40]:
tensor * 10 # numpy-like

tensor([10, 20, 30])

In [41]:
print(tensor * 10)
print(torch.mul(tensor, 10))
print(torch.multiply(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])
tensor([10, 20, 30])


In [42]:
# Matrix multiplication @ https://www.mathsisfun.com/algebra/matrix-multiplying.html

tensor = torch.tensor([[1, 2], [3, 4]])

tensor

tensor([[1, 2],
        [3, 4]])

In [46]:
tensor.T # Transpose

tensor([[1, 3],
        [2, 4]])

In [47]:
tensor * tensor # Element-wise multiplication

tensor([[ 1,  4],
        [ 9, 16]])

In [48]:
# Matrix multiplication 1 

torch.matmul(tensor, tensor) # Matrix multiplication

tensor([[ 7, 10],
        [15, 22]])

In [49]:
# Matrix multiplication 2

torch.mm(tensor, tensor) # "M"atrix "m"ultiplication

tensor([[ 7, 10],
        [15, 22]])

In [50]:
# Matrix multiplication 3

tensor @ tensor # 행렬곱 연산자 @

tensor([[ 7, 10],
        [15, 22]])

In [51]:
tensor = torch.tensor([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
# tensor = torch.arange(1, 13).reshape(2, 6)

tensor

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [52]:
tensor.reshape(3, 4) # 모양(shape) 다시 바꾸기 (numpy-like)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

<br>
<br>

# 3. Pytorch tensor <-> Numpy array


<br>
<br>

### 1) Pytorch tensor -> Numpy array 
<br>

#### -> tensor.**numpy**() 활용

In [53]:
random_tensor = torch.rand(size=(2, 3), dtype=torch.float16)

random_tensor

tensor([[0.9780, 0.9297, 0.5649],
        [0.3911, 0.9609, 0.1797]], dtype=torch.float16)

In [54]:
np_array = random_tensor.numpy() # tensor 변수를 "numpy"로

np_array 

array([[0.978 , 0.9297, 0.565 ],
       [0.391 , 0.961 , 0.1797]], dtype=float16)

In [55]:
type(np_array)

numpy.ndarray

<br>
<br>

### 2) Numpy array -> Pytorch tensor
<br>

#### -> torch.**from_numpy**() 활용

In [56]:
import numpy as np

In [57]:
array = np.arange(12.0).reshape(2, 6)

array

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [58]:
torch_tensor = torch.from_numpy(array) # "numpy 변수로부터"

torch_tensor

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]], dtype=torch.float64)

In [59]:
type(torch_tensor)

torch.Tensor

<br>
<br>

# (Appendix 1) Reproducibility 


In [60]:
seed = 42 

torch.manual_seed(seed=seed) 

# torch.cuda.manual_seed(seed=seed) # for GPU 

In [61]:
torch.manual_seed(seed=seed) 

random_tensor_1 = torch.rand(3, 4)

random_tensor_1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [62]:
# rand() 함수 호출 시마다 seed 값을 다시금 세팅해주어야 합니다. (아래 라인 주석 처리 시 다른 tensor가 만들어짐)
torch.manual_seed(seed=seed) # 주석 처리 후 다시 실행해 테스트

random_tensor_2 = torch.rand(3, 4)

random_tensor_2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])